// Generated by prebuild.mjs - DO NOT EDIT MANUALLY
export interface SceneDuration {
  num: number;
  fileName: string;
  name: string;
  durationSec: number;
  durationFrames: number;
}

export const SCENE_DURATIONS: SceneDuration[] = [
  {
    "num": 1,
    "fileName": "scene-01-landing.mp3",
    "name": "landing",
    "durationSec": 40.071836734693875,
    "durationFrames": 1203
  },
  {
    "num": 4,
    "fileName": "scene-04-kpis.mp3",
    "name": "kpis",
    "durationSec": 99.97061224489796,
    "durationFrames": 3000
  },
  {
    "num": 5,
    "fileName": "scene-05-charts.mp3",
    "name": "charts",
    "durationSec": 90.27918367346939,
    "durationFrames": 2709
  },
  {
    "num": 6,
    "fileName": "scene-06-drilldown.mp3",
    "name": "drilldown",
    "durationSec": 27.76816326530612,
    "durationFrames": 834
  },
  {
    "num": 7,
    "fileName": "scene-07-skillmatrix.mp3",
    "name": "skillmatrix",
    "durationSec": 67.1869387755102,
    "durationFrames": 2016
  },
  {
    "num": 8,
    "fileName": "scene-08-skill-assessment.mp3",
    "name": "skill-assessment",
    "durationSec": 30.328163265306124,
    "durationFrames": 910
  },
  {
    "num": 12,
    "fileName": "scene-12-management.mp3",
    "name": "management",
    "durationSec": 80.14367346938775,
    "durationFrames": 2405
  },
  {
    "num": 13,
    "fileName": "scene-13-defects-crud.mp3",
    "name": "defects-crud",
    "durationSec": 112.74448979591837,
    "durationFrames": 3383
  },
  {
    "num": 15,
    "fileName": "scene-15-actionplans.mp3",
    "name": "actionplans",
    "durationSec": 140.90448979591838,
    "durationFrames": 4228
  },
  {
    "num": 17,
    "fileName": "scene-17-quick-attendance.mp3",
    "name": "quick-attendance",
    "durationSec": 66.08979591836734,
    "durationFrames": 1983
  },
  {
    "num": 30,
    "fileName": "scene-30-outro.mp3",
    "name": "outro",
    "durationSec": 23.588571428571427,
    "durationFrames": 708
  }
];

export const TOTAL_FRAMES = 23379;
